State.create!([
  {name: "Aguascalientes"},
  {name: "Campeche"},
  {name: "Colima"},
  {name: "Chiapas"},
  {name: "Chihuahua"},
  {name: "Durango"},
  {name: "Guanajuato"},
  {name: "Guerrero"},
  {name: "Hidalgo"},
  {name: "Jalisco"},
  {name: "México"},
  {name: "Morelos"},
  {name: "Nayarit"},
  {name: "Oaxaca"},
  {name: "Puebla"},
  {name: "Querétaro"},
  {name: "Sinaloa"},
  {name: "Sonora"},
  {name: "Tabasco"},
  {name: "Tamaulipas"},
  {name: "Tlaxcala"},
  {name: "Yucatán"},
  {name: "Zacatecas"},
  {name: "Baja California"},
  {name: "Baja California Sur"},
  {name: "Coahuila de Zaragoza"},
  {name: "Distrito Federal"},
  {name: "Michoacán de Ocampo"},
  {name: "Nuevo León"},
  {name: "Quintana Roo"},
  {name: "San Luis Potosí"},
  {name: "Veracruz de Ignacio de la Llave"}
])
